# Automated Factor Slice Sampler (<a name='afss'>AFSS</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The acceptance rate is 1.', 'This is a widely applicable, general-purpose algorithm.','This algorithm is easy for a beginner. There are several algorithm specifications, and the defaults are recommended for automatic use.','Yes, when `A`=0. See below.', 'Multivariate proposals with componentwise evaluation.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>


The Automated Factor Slice Sampler of Tibbits et al. (2014) is an extension of the componentwise slice sampler in which linear correlation between parameters is accounted for and the interval widths are tuned. This results in a componentwise slice sampler that is faster than a traditional componentwise slice sampler because less evaluations are necessary to estimate the slice boundaries, and it samples efficiently in high-dimensional models with continuous parameters.

AFSS has five algorithm specifications: `A` accepts a scalar that indicates the iteration in which adaptation will cease, and defaults to Inf. `B` is for blockwise sampling, defaults to NULL, and otherwise accepts a list of parameter positions, in which each list component is a block. Blocks are processed sequentially, but the order of parameters is selected randomly within each block, and each block must contain at least two parameters. The `m` specification accepts either a scalar integer or a vector equal in length to the number of parameters that indicates the maximum number of steps. It defaults to 100 and must be in [1, ∞]. The `n` specification accepts a scalar that indicates the total previous number of adaptive iterations, and defaults to 0. Finally, w accepts either a scalar or a vector equal in length to the number of parameters, and is initial step size, which defaults to 1 and must be in (0, ∞).

AFSS performs two kinds of adaptation. While adaptive, each iteration AFSS collects an approximation of the covariance of the parameters via a scatter matrix. Periodically, eigenvectors are estimated from the approximated covariance matrix. More parameters results in less frequent adaptation. Each iteration, componentwise evaluation is performed as per a componentwise sampler. However, after the first eigenvalue estimation, all parameters are updated for each componentwise evaluation, which results in a sampler that is not truly multivariate or componentwise. Each parameter is updated in turn, but all other parameters are also updated due to linear correlations with the current parameter. Also, after each estimation of eigenvalues, the interval widths are tuned toward an equal probability of interval expansion during the step-out phase and interval shrinkage during rejection sampling. As the number of parameters increases, so does the computational cost of estimating eigenvalues, and blockwise sampling becomes more practical in high-dimensional models.

While AFSS is efficient with linear relationships, it may be inefficient due to nonlinear relationships. The AFSS algorithm is slower per iteration than multivariate samplers, but typically improves more per iteration than most algorithms. To date, testing indicates AFSS is remarkably efficient. AFSS is acceptable as a final algorithm when non-adaptive samples are drawn.

## References

- Tibbits M, Groendyke C, Haran M, and Liechty J (2014). "Automated Factor Slice Sampling". Journal of Computational and Graphical Statistics, 23(2), 543-563.


## See Also

- [Slice](#slice)