# Delayed Rejection Metropolis (<a name='drm'>DRM</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The optimal acceptance rate is based on the multivariate normality of the marginal posterior distributions, and ranges from 44% for one parameter to 23.4% for five or more parameters. The observed acceptance rate may be suitable in the interval [15%,50%].', 'This is a widely applicable, general-purpose algorithm. The proposal covariance matrix should have been solved with an adaptive algorithm such as DRAM.','This algorithm is easy for a beginner when the proposal covariance has been tuned with another algorithm. Otherwise, it may be tedious for the user to tune the proposal covariance matrix.','Yes.', 'Multivariate. Whenever a proposal is rejected, an alternate proposal is attempted.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>

The Delayed Rejection Metropolis (DRM or DR) algorithm is a Random-Walk Metropolis (RWM) with one, small twist. Whenever a proposal is rejected, the DRM algorithm will try one or more alternate proposals, and correct for the probability of this conditional acceptance. By delaying rejection, autocorrelation in the chains may be decreased, and the algorithm is encouraged to move. The additional calculations may slow each iteration of the algorithm in which the first set of proposals is rejected, but it may also converge faster. For more information on DRM, see Mira (2001).

DRM does not have any algorithm specifications.

DRM may be considered to be an adaptive MCMC algorithm, because it adapts the proposal based on a rejection. However, DRM does not violate the Markov property, because the proposal is based on the current state. DRM is not considered to be an adaptive MCMC algorithm here, because it is not adapting to the target distribution by considering previous states in the Markov chain, but merely makes more attempts from the current state.

LaplacesDemon also temporarily shrinks the proposal covariance arbitrarily by 50% for delayed rejection. A smaller proposal covariance is more likely to be accepted, and the goal of delayed rejection is to increase acceptance. In the long-term, a proposal covariance that is too small is undesirable, and so it is only used in this case to assist acceptance.

Since DRM is non-adaptive, it is suitable as a final algorithm.

## References

- Mira A (2001). "On Metropolis-Hastings Algorithms with Delayed Rejection." Metron, LIX(3–4), 231-241.

## See Also

- [RMW](#rmw)

