# <a name='ram'>Robust Adaptive Metropolis</a>

(<a name='ram'>RAM</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The user specifies the target acceptance rate, α* (23.4% is recommended). The observed acceptance rate may be suitable in the interval [15%,50%].', 'This is a widely applicable, general-purpose algorithm that is best suited to models with a small to medium number of parameters, or a larger number of blocked parameters. The proposal covariance matrix must be solved, and this matrix grows with the number of parameters.','This algorithm is relatively easy for a beginner. It has few algorithm specifications, and these are easy to specify. However, since it is adaptive, the user must regard diminishing adaptation.','User Discretion. The RWM algorithm is recommended as the final algorithm, though RAM may be used if diminishing adaptation occurs and adaptation ceases effectively.', 'Blockwise or Multivariate.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>

The Adaptive Metropolis (AM) and Adaptive-Mixture Metropolis (AMM) algorithms adapt the scale of the proposal distribution to attain a theoretical acceptance rate. However, these algorithms are unable to adapt to the shape of the target distribution. The Robust Adaptive Metropolis (RAM) algorithm estimates the shape of the target distribution and simultaneously coerces the acceptance rate (Vihola 2011). If the acceptance probability, α, is less (or greater) than an acceptance rate target, α∗, then the proposal distribution is shrunk (or expanded). Matrix S is computed as a rank one Cholesky update. Therefore, the algorithm is computationally efficient up to a relatively high dimension. The AM and AMM algorithms require a burn-in period prior to adaptation, so that these algorithms can adapt to the sample covariance. RAM does not require a burn-in period prior to adaptation. RAM allows the user the option of using the traditional normally-distributed proposals, or t-distributed proposals for heavier-tailed target densities. Unlike AM and AMM, RAM can cope with targets having arbitrarily heavy tails, and handles multimodal targets better than AM. The user is still assumed to know and specify the target acceptance rate.

RAM has five algorithm specifications: `alpha.star` is the target acceptance rate, `B` optionally accepts a list of blocked parameters and defaults to NULL, `Dist` is the target distribution as either "N" for normal or "t" for the Student t with 5 degrees of freedom, `gamma` accepts a scalar in the interval (0.5,1] and controls the decay of adaptation (0.66 is recommended), and `n` is the number of previous iterations. RAM adapts only when the variance-covariance matrix is positive-definite.

The advantages of RAM over AMM are that RAM does not require a burn-in period before it can begin to adapt, RAM is more likely to better handle multimodal or heavy-tailed targets, RAM also adapts to the shape of the target distributions, and attempts to coerce the acceptance rate. The advantages of RAM over Adaptive Metropolis-within-Gibbs (AMWG) are that RAM takes correlations into account, and is much faster to update each iteration. The disadvantage of RAM compared to AMWG is that more information must be learned in the covariance matrix to adapt properly, and frequent adaptation may be desirable, but slow. If RAM is used for adaptation, then the final, non-adaptive algorithm should be Random-Walk Metropolis (RWM).

## References

- Vihola M (2011). "Robust Adaptive Metropolis Algorithm with Coerced Acceptance Rate." In Forthcoming (ed.), Statistics and Computing, p. 1-12. Springer, Netherlands.

## See Also

- [AM](#am)
- [AMM](#amm)
- [AMWG](#amwg)
- [RWM](#rwm)

