# <a name='thmc'>Tempered Hamiltonian Monte Carlo</a>

(<a name='thmc'>THMC</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The optimal acceptance rate is 65% when L > 1, or 57.4% when L = 1. The observed acceptance rate may be suitable in the interval [60%,70%] when L > 1, or [40%,80%] when L = 1.', 'This is a widely applicable, general-purpose algorithm that is best suited to models with a small number of parameters. The number of model evaluations per iteration increases with the number of parameters.','This algorithm is difficult for a beginner. It has a several algorithm specifications, and these are difficult to tune.','Yes.', '	Multivariate. Proposals are multivariate only in the sense that proposals for multiple parameters are generated at once. Each iteration involves numerous proposals, due to partial derivatives and L.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>

The Tempered Hamiltonian Monte Carlo (THMC) algorithm is an extension of Hamiltonian Monte Carlo (HMC) to include another algorithm specification: Temperature, which must be positive. When greater than 1, the algorithm should explore more diffuse distributions, and may be helpful with multimodal distributions.

THMC has four algorithm specifications: step-size `epsilon`, the number `L` of leapfrog steps, an optional mass matrix `M`, and `Temperature`. Algorithm specifications are the same as for HMC, with the exception of temperature, which is described below.

There are a variety of ways to include tempering in HMC, and this algorithm, named here as THMC, uses "tempered trajectory", as described by Neal (2011). When L > 1 and during the first half of the leapfrog steps, the momentum is increased (heated) by multiplying it by √T, where T is temperature, each leapfrog step. In the last half of the leapfrog steps, the momentum decreases (is cooled down) by dividing it by √T. The momentum is largest in the middle of the leapfrog steps, where mode-switching behavior becomes most likely to occur. This preserves the trajectory, εL.

As with HMC, THMC is a difficult algorithm to tune. Since THMC is non-adaptive, it is sufficient as a final algorithm.

## References

- Neal R (2011). "MCMC for Using Hamiltonian Dynamics." In S Brooks, A Gelman, G Jones, M Xiao-Li (eds.), Handbook of Markov Chain Monte Carlo, p. 113-162. Chapman & Hall, Boca Raton, FL.

## See Also

- [HMC](#hmc)
- [MALA](#mala)

