# Updating Sequential Adaptive Metropolis-within-Gibbs (<a name='usamwg'>USAMWG</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The optimal acceptance rate is 44%, and is based on the univariate normality of each marginal posterior distribution. The observed acceptance rate may be suitable in the interval [15%,50%].', 'This algorithm is applicable with state-space models (SSMs), including dynamic linear models (DLMs).','This algorithm is relatively easy for a beginner. It has few algorithm specifications. However, since it is adaptive, the user must regard diminishing adaptation.','User Discretion. The USMWG algorithm is recommended as the final algorithm, though USAMWG may be used if diminishing adaptation occurs and adaptation ceases effectively.', 'Componentwise.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>

The Updating Sequential Adaptive Metropolis-within-Gibbs (USAMWG) is for state-space models (SSMs), including dynamic linear models (DLMs). After a model is fit with Sequential Adaptive Metropolis-within-Gibbs (SAMWG) and Sequential Metropolis-within-Gibbs (SMWG), and information is later obtained regarding the first future state predicted by the model, the USAMWG algorithm may be applied to update the model given the new information. In SSM terminology, updating is filtering and predicting. This is more efficient than re-estimating the entire model each time new information is obtained.

For example, suppose a time-series of daily values was fit with the SAMWG algorithm. Let's also suppose the last day in the model sample was a Monday, and that one-step ahead forecasts are produced, so the model predicted Tuesday. After the actual value for Tuesday is known, it may be included in the model. Using USAMWG, the latest Tuesday is filtered and Wednesday is forecast, while the days of the original model sample are not estimated again.

## References

- none

## See Also

- [SAMWG](#samwg)
- [SMWG](#smwg)

