# Updating Sequential Metropolis-within-Gibbs (<a name='usmwg'>USMWG</a>)

<br>
```{r, echo=FALSE}
pander::pander(
  data.frame(
    Aspect = c('Acceptance Rate', 'Applications', 'Difficulty', 'Final Algorithm?', 'Proposal'),
    Description = c('The optimal acceptance rate is 44%, and is based on the univariate normality of each marginal posterior distribution. The observed acceptance rate may be suitable in the interval [15%,50%].', 'This algorithm is applicable with state-space models (SSMs), including dynamic linear models (DLMs).','This algorithm is relatively easy for a beginner when the proposal variance has been tuned with the USAMWG algorithm. Otherwise, it may be tedious for the user to tune the proposal variance.','Yes.', 'Componentwise.')),
  justify='left', style='multiline', split.cells=c(17,83), split.tables=Inf)
```

<br>

The Updating Sequential Metropolis-within-Gibbs (USMWG) algorithm is the non-adaptive version of the USAMWG algorithm, and is used for final sampling when updating state-space models (SSMs).

For example, suppose a time-series of daily values was fit with the SAMWG algorithm, and SMWG may have been used for final samples. Let's also suppose the last day in the model sample was a Monday, and that one-step ahead forecasts are produced, so the model predicted Tuesday. After the actual value for Tuesday is known, it may be included in the model. Using USAMWG, the latest Tuesday is filtered and Wednesday is forecast, while the days of the original model sample are not estimated again. USMWG may then be used for final samples.


## References

- none

## See Also

- [USAMWG](#usamwg)

